# Generated by Django 5.2.15 on 2026-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenure_months', models.PositiveIntegerField()),
                ('monthly_charges', models.FloatField()),
                ('support_tickets', models.PositiveIntegerField()),
                ('contract', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('will_churn', models.BooleanField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
